version: '2'
services:
  mongo: 
    image: mongo:3.2.4
    container_name: s63a-mongo
    ports: 
      - "27017:27017" 

  mysql: 
    image: mysql:5.7.11
    container_name: s63a-mysql
    environment: 
      - MYSQL_ROOT_PASSWORD=s63a
      - MYSQL_DATABASE=s63a
      - MYSQL_USER=s63a
      - MYSQL_PASSWORD=s63a
    ports: 
      - "3306:3306"

  phpmyadmin: 
    image: phpmyadmin/phpmyadmin
    container_name: s63a-phpmyadmin
    ports: 
      - "8000:80"
    links: 
      - mysql:db